### ISSUE TITLE
Unify seed structure

### ISSUE THREAD

**Issue by dwhan89** [ACTCollaboration/actsims#27]
Each type of simulation (ex: CMB, lensing potential, foregrounds etc) needs unique seed in tuple. Currently, there is no central location inside of the code keeping a track of different kinds of seeds. This is very error-prone, and messing up seed structure can introduce subtle bugs that would be hard to track down. Let's introduce a unified seed structure once for all.

**Comment by dwhan89** [comment]
Currently used seeds

- CMB : `(set_idx, 0, 0, sim_idx)`
- Phi   :  `(set_idx, 0, 2, sim_idx)`
- 15mJy Foreground : `(set_idx, 0, 1, sim_idx, 0)` 
- 100mJy Foreground : `(set_idx, 0, 1, sim_idx, 1)` 
- 'src_free' Foreground: `(set_idx, 0, 1, sim_idx, 2)`  
- Poisson PT srcs:  `(set_idx, 0, 4, sim_num)`

**Comment by msyriac** [comment]
Also noise sim seeds: https://github.com/simonsobs/soapack/blob/master/soapack/interfaces.py#L140

- Noise: (set_idx, 0, 3, sim_num,experiment_id, season, patch, array,splitnum)

The noise sim seed stuff should be moved from soapack to actsims, but in a way that different experiments are distinguished.

**Comment by dwhan89** [comment]
PR filed for the issue (https://github.com/ACTCollaboration/actsims/pull/28/commits)

**Comment by ajvanengelen** [comment]
Looks great to me, thanks for moving this stuff into a nicely-defined class!
Alex

**Comment by ajvanengelen** [comment]
PS I can sign off on this, Mat could you let me know if you agree (i.e. does it work well with your noise sim stuff?)

**Comment by ajvanengelen** [comment]
Oh actually, could you delete the old simTools.py?  I think it is now fully deprecated (I had been keeping it around for this index stuff).

Also, could you do me a favor since you have eyes on it, and also change the phiSeed and cmbSeed in the CMB sim generation script to call the new routine.  It’s this line https://github.com/ACTCollaboration/actsims/blob/3062dc1a27fd37bf358b5638c56bab80a3e02f46/bin/signalSims.py#L85 <https://github.com/ACTCollaboration/actsims/blob/3062dc1a27fd37bf358b5638c56bab80a3e02f46/bin/signalSims.py#L85>

Thanks!
Alex

**Comment by dwhan89** [comment]
No problem! It's done.

**Comment by ajvanengelen** [comment]
Great - thanks!
