### ISSUE TITLE
Submaps

### ISSUE THREAD

**Issue by msyriac** [ACTCollaboration/actsims#5]
Is there any particular reason why there are submap operations?

Why not let the geometry of the original map (output of the map-maker) determine the geometry of the noise simulations as well? You can always choose a mask when calculating noise power spectra to restrict information from a particular region (e.g. Steve's cross-linked regions). Submaps introduce another variable that require coordination from ini files, and also possibilities of physical to pixel coordinate rounding ambiguities between codes. 

One good reason I can think of is we want to be ready for S16, and for those full-sky maps, it makes sense to define submap regions (if we continue to do patch by patch analysis).

**Comment by dwhan89** [comment]
I remember discussing on one of our lensing telecons that we are going to use Simone's routine to generate noise sims. So this might be an issue?

**Comment by ajvanengelen** [comment]
Thanks for bringing this up.

There is no reason in principle that we need to work with submaps, (aside from concerns with memory usage).  In practice, the script that makes the templates (2d power spectra and hit maps for coadds) first cuts submaps, then makes coadds.  I am actually not sure if it would work without taking cutouts because as written all the splits need to be in memory at once.

I don’t think that the sim code itself (i.e. in this repo) assumes anything about submaps — it should work fine if fed larger hitmaps as templates.

Alex

**Comment by ajvanengelen** [comment]
The maps no longer use cutouts.  Closing
